# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:01:45+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, Field


class FieldVCustomPricesRulesPostRequest(BaseModel):
    email: Optional[Any] = Field('', description="User's email", title='email')
    orderType: Optional[str] = Field('', description='Order type', title='orderType')
    pricetable: str = Field(
        ...,
        description='Name of the Price Table associated with the scenario',
        title='pricetable',
    )
    state: Optional[str] = Field('', description='Delivery location', title='state')


class FieldVCustomPricesRulesPostResponse(BaseModel):
    email: Optional[Any] = Field('', description="User's email", title='email')
    id: int = Field(..., description='Price association ID', title='id')
    orderType: Optional[str] = Field('', description='Order type', title='orderType')
    pricetable: str = Field(
        ...,
        description='Name of the Price Table associated with the scenario',
        title='pricetable',
    )
    state: Optional[str] = Field('', description='Delivery location', title='state')


class FieldVCustomPricesRulesPriceAssociationIdGetResponse(BaseModel):
    email: Optional[Any] = Field('', description="User's email", title='email')
    id: int = Field(..., description='Price association ID', title='id')
    orderType: Optional[str] = Field('', description='Order type', title='orderType')
    pricetable: str = Field(
        ...,
        description='Name of the Price Table associated with the scenario',
        title='pricetable',
    )
    state: Optional[str] = Field('', description='Delivery location', title='state')


class FieldVCustomPricesRulesPriceAssociationIdPutRequest(BaseModel):
    orderType: str = Field(..., description='Order type', title='orderType')
    pricetable: str = Field(
        ...,
        description='Name of the Price Table associated with the scenario',
        title='pricetable',
    )
    state: str = Field(..., description='Delivery location', title='state')


class FieldVCustomPricesRulesPriceAssociationIdPutResponse(BaseModel):
    email: Optional[Any] = Field('', description="User's email", title='email')
    id: int = Field(..., description='Price association ID', title='id')
    orderType: Optional[str] = Field('', description='Order type', title='orderType')
    pricetable: str = Field(
        ...,
        description='Name of the Price Table associated with the scenario',
        title='pricetable',
    )
    state: Optional[str] = Field('', description='Delivery location', title='state')


class FieldModel(BaseModel):
    name: str = Field(..., description='Criteria name', title='name')
    type: str = Field(..., description='Criteria type', title='type')


class FieldVCustomPricesSessionSchemaGetResponse(BaseModel):
    fields: List[FieldModel] = Field(
        ..., description='Order Configuration criteria', title='fields'
    )
    useEmail: Optional[bool] = Field(
        True,
        description="If the custom price should use the user's e-mail to validate it",
        title='useEmail',
    )


class FieldVCustomPricesSessionSchemaPostRequest(BaseModel):
    fields: List[FieldModel] = Field(
        ..., description='Order Configuration criteria', title='fields'
    )
    useEmail: Optional[bool] = Field(
        True,
        description="If the custom price should use the user's e-mail to validate it",
        title='useEmail',
    )


class FieldVCustomPricesSessionSchemaPostResponse(BaseModel):
    fields: List[FieldModel] = Field(
        ..., description='Order Configuration criteria', title='fields'
    )
    useEmail: Optional[bool] = Field(
        True,
        description="If the custom price should use the user's e-mail to validate it",
        title='useEmail',
    )


class CustomSessionKeys(BaseModel):
    value: str = Field(..., description='Order Configuration criteria', title='value')


class Public(BaseModel):
    customSessionKeys: CustomSessionKeys = Field(
        ...,
        description='Contains every schema criteria. This is a serialized JSON object',
        title='customSessionKeys',
    )


class SessionsPostRequest(BaseModel):
    public: Public = Field(
        ..., description='Object to register session criteria', title='public'
    )
